name: asciidoctor-ghpages

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Generate rcrs-server HTML
      run: asciidoctor -b html5 -r asciidoctor-bibtex -a bibtex-file=docs/rcrs-server/references.bib docs/rcrs-server/rcrs-server-manual.adoc -o docs/rcrs-server/index.html
    - name: Generate rcrs-server PDF
      run: asciidoctor-pdf -r asciidoctor-bibtex -r asciidoctor-mathematical -a bibtex-file=docs/rcrs-server/references.bib -a mathematical-format=svg -a optimize -a pdf-theme=docs/resources/themes/manual.yml -a pdf-fontsdir=docs/resources/fonts docs/rcrs-server/rcrs-server-manual.adoc -o docs/rcrs-server/rcrs-server-manual.pdf
    - name: Generate map-creation HTML
      run: asciidoctor -b html5 -r asciidoctor-bibtex -a bibtex-file=docs/map-creation/references.bib docs/map-creation/map-creation-manual.adoc -o docs/map-creation/index.html
    - name: Generate map-creation PDF
      run: asciidoctor-pdf -r asciidoctor-bibtex -r asciidoctor-mathematical -a bibtex-file=docs/map-creation/references.bib -a mathematical-format=svg -a optimize -a pdf-theme=docs/resources/themes/manual.yml -a pdf-fontsdir=docs/resources/fonts docs/map-creation/map-creation-manual.adoc -o docs/map-creation/map-creation-manual.pdf
    - name: Generate rcrs-competition HTML
      run: asciidoctor -b html5 -r asciidoctor-bibtex -a bibtex-file=docs/rcrs-competition/references.bib docs/rcrs-competition/rcrs-competition-manual.adoc -o docs/rcrs-competition/index.html
    - name: Generate rcrs-competition PDF
      run: asciidoctor-pdf -r asciidoctor-bibtex -r asciidoctor-mathematical -a bibtex-file=docs/rcrs-competition/references.bib -a mathematical-format=svg -a optimize -a pdf-theme=docs/resources/themes/manual.yml -a pdf-fontsdir=docs/resources/fonts docs/rcrs-competition/rcrs-competition-manual.adoc -o docs/rcrs-competition/rcrs-competition-manual.pdf
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
